FROM node:20-alpine

WORKDIR /app

COPY package.json package-lock.json* ./
RUN npm ci

COPY . .

ARG ARK_API_KEY
ARG NEXT_PUBLIC_ANALYTICS_URL
ENV ARK_API_KEY=$ARK_API_KEY
ENV NEXT_PUBLIC_ANALYTICS_URL=$NEXT_PUBLIC_ANALYTICS_URL

RUN npm run build

EXPOSE 3000

CMD ["npm", "start"]
